### PR TITLE
Add PORT to settings.h

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by cmouse** [comment]
Hi!

Thank you for your pull request, can you explain why this is needed?

**Comment by cmouse** [comment]
I wonder if it would make sense to default to 143 instead?

**Comment by emersion** [comment]
`conf.port` defaults to 0 so that's why I picked this value. 143 wouldn't be appropriate for POP: https://github.com/dovecot/imaptest/blob/1425ad0caaf727418136cde776241e4cbcf59b81/src/pop3-client.c#L424

**Comment by cmouse** [comment]
ok

**Review by cmouse — APPROVED** [review]

**Pull request merged**
